### PR TITLE
Theme api

### LINKED ISSUE #33: Rest api for themes
how did i forget about this one

### PR DESCRIPTION
**Pull request by ajm188**
had to make `filepath` `allow_blank` in the serializer to get the tests passing. not 100% sure what the implications are for this.

also, i apparently forgot to rebase the branch, so i will do that and update this branch.

closes #33

### CODE REVIEW

**Comment by ajm188** [comment]
aaaaaand updated

**Comment by dealie16** [comment]
👍 other than the tests not passing

**Comment by ajm188** [comment]
@dealie16 fixed and updated

**Comment by dealie16** [comment]
👍

**Comment by ajm188** [comment]
update again

**Comment by dealie16** [comment]
:shipit:

**Pull request merged**
