### PR TITLE
Obfuscate django by using .php URLs

### PR DESCRIPTION
**Pull request by brenns10**
You don't want to let users know that you're using Django.  So I improved your security by adding the `.php` extension to all your URLs.

Security through obscurity!

### CODE REVIEW

**Comment by brenns10** [comment]
Also, this incidentally resolves #4.

**Comment by brenns10** [comment]
screenshot_20160301_170056

Works on my machine.

**Comment by ajm188** [comment]
I agree this _works_, but I question it's usefulness :stuck_out_tongue:

**Comment by brenns10** [comment]
It might be even more convincing if the URL's were more like this:

`/category.php?user=stephen&project=test&action=create`

Unfortunately, you can't quickly redefine Django URLs to use GET parameters instead of regular expression captures in the URL.

However, I like the charm of this URL layout.  It looks like whenever you create a new project, a PHP script somewhere creates a corresponding directory hierarchy and copies in all of the PHP scripts necessary to manage that project.  Which totally sounds like something I would have thought of doing when I wrote PHP (circa 2011).

**Comment by ajm188** [comment]
You can actually do this in javascript :D

**Comment by jpcjr** [comment]
:+1:

**Comment by jpcjr** [comment]
:ship: :it:

**Comment by ajm188** [comment]
lol
lg2nm (looks good to never merge)

**Comment by ajm188** [comment]
Closing due to ... so many reasons :stuck_out_tongue_closed_eyes:

**Comment by brenns10** [comment]
http://www.nooooooooooooooo.com/

**Comment by ajm188** [comment]
Greatest reaction to closing a PR ever

**Pull request closed without merging**
